// Package {% raw %}{{ .Package }}{% endraw %}.
//
// Code generated by {{ cookiecutter.module_name }} DO NOT EDIT.
// The {{ cookiecutter.__project_name }} version: {% raw %}{{ .Version }}{% endraw %}
{% raw %}
// Source: {{ .SourcePath }}
package {{ .Package }}

// TODO: Generated code template goes here.
{% endraw %}